# Generated by Django 5.2.4 on 2025-08-05 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='delivery_date',
            field=models.DateTimeField(blank=True, help_text='When this memory should be delivered', null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='delivery_type',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled'), ('recurring', 'Recurring'), ('time_locked', 'Time Locked')], default='immediate', help_text='How this memory should be delivered', max_length=20),
        ),
        migrations.AddField(
            model_name='memory',
            name='encrypted_content',
            field=models.TextField(blank=True, help_text='Encrypted version of the content'),
        ),
        migrations.AddField(
            model_name='memory',
            name='is_delivered',
            field=models.BooleanField(default=False, help_text='Whether this memory has been delivered'),
        ),
        migrations.AddField(
            model_name='memory',
            name='is_time_locked',
            field=models.BooleanField(default=False, help_text='Whether this memory is time-locked'),
        ),
        migrations.AddField(
            model_name='memory',
            name='recurring_pattern',
            field=models.JSONField(blank=True, help_text='Recurring delivery pattern', null=True),
        ),
    ]
