# Generated by Django 5.2.4 on 2025-08-05 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0001_initial'),
    ]

    operations = [
        # Update existing records to have proper defaults for NOT NULL fields
        migrations.RunSQL(
            # Forward SQL: Update existing records with defaults
            """
            UPDATE memory_assistant_memory 
            SET delivery_type = 'immediate' 
            WHERE delivery_type IS NULL;
            
            UPDATE memory_assistant_memory 
            SET encrypted_content = '' 
            WHERE encrypted_content IS NULL;
            
            UPDATE memory_assistant_memory 
            SET is_delivered = false 
            WHERE is_delivered IS NULL;
            
            UPDATE memory_assistant_memory 
            SET is_time_locked = false 
            WHERE is_time_locked IS NULL;
            """,
            # Reverse SQL: No reverse operation needed
            ""
        ),
    ]
