# Generated by Django 5.2.4 on 2025-08-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0002_memory_delivery_date_memory_delivery_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='memory_type',
            field=models.CharField(choices=[('general', 'General'), ('work', 'Work'), ('personal', 'Personal'), ('health', 'Health'), ('finance', 'Finance'), ('learning', 'Learning'), ('idea', 'Idea'), ('reminder', 'Reminder')], default='general', max_length=50),
        ),
    ]
