# Generated by Django 5.2.4 on 2025-08-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0003_alter_memory_memory_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='encrypted_content',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='is_time_locked',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='recurring_pattern',
        ),
        migrations.AlterField(
            model_name='memory',
            name='memory_type',
            field=models.CharField(choices=[('general', 'General'), ('work', 'Work'), ('personal', 'Personal'), ('learning', 'Learning'), ('idea', 'Idea'), ('reminder', 'Reminder')], default='general', max_length=50),
        ),
    ]
