# Generated by Django 5.2.4 on 2025-08-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0004_remove_delivery_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='ai_reasoning',
            field=models.TextField(blank=True, help_text='AI reasoning for categorization'),
        ),
    ]
