# Generated by Django 5.2.4 on 2025-08-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0003_add_delivery_fields_fake'),
        ('memory_assistant', '0005_add_ai_reasoning_field'),
    ]

    operations = [
    ]
