# Generated by Django 5.2.4 on 2025-08-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0006_merge_20250805_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='delivery_type',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='encrypted_content',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='is_delivered',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='is_time_locked',
        ),
    ]
