# Generated by Django 5.2.4 on 2025-08-08 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0007_add_delivery_fields_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='Whether this memory is recurring'),
        ),
        migrations.AddField(
            model_name='memory',
            name='next_delivery_date',
            field=models.DateTimeField(blank=True, help_text='Next occurrence of this recurring memory', null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='parent_memory',
            field=models.ForeignKey(blank=True, help_text='Parent memory for recurring instances', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recurring_instances', to='memory_assistant.memory'),
        ),
        migrations.AddField(
            model_name='memory',
            name='recurrence_days',
            field=models.JSONField(blank=True, default=list, help_text='Days of week for weekly recurrence (0=Monday, 6=Sunday)'),
        ),
        migrations.AddField(
            model_name='memory',
            name='recurrence_end_date',
            field=models.DateTimeField(blank=True, help_text='End date for recurring memories', null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='recurrence_interval',
            field=models.IntegerField(default=1, help_text='Interval between recurrences (e.g., every 2 days)'),
        ),
        migrations.AddField(
            model_name='memory',
            name='recurrence_type',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly'), ('custom', 'Custom')], help_text='Type of recurrence pattern', max_length=20, null=True),
        ),
    ]
