# Generated by Django 5.2.4 on 2025-08-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0007_remove_delivery_fields_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='scheduled_date',
            field=models.DateField(blank=True, help_text='Date when this memory should be displayed or acted upon', null=True),
        ),
    ]
