# Generated by Django 5.2.4 on 2025-08-06 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0008_memory_scheduled_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='scheduled_date',
        ),
    ]
