# Generated by Django 5.2.4 on 2025-08-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0008_memory_is_recurring_memory_next_delivery_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='next_delivery_date',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='parent_memory',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='recurrence_days',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='recurrence_end_date',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='recurrence_interval',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='recurrence_type',
        ),
        migrations.AlterField(
            model_name='memory',
            name='delivery_type',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('scheduled', 'Scheduled'), ('conditional', 'Conditional')], default='immediate', help_text='How this memory should be delivered', max_length=50),
        ),
    ]
