# Generated by Django 5.2.4 on 2025-08-08 16:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0009_remove_recurring_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WakeupCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this wakeup call is active')),
                ('wakeup_time', models.TimeField(help_text='Time to wake up')),
                ('days_of_week', models.JSONField(default=list, help_text='Days of week for wakeup call (0=Monday, 6=Sunday)')),
                ('message', models.TextField(blank=True, help_text='Custom wakeup message')),
                ('include_todays_memories', models.BooleanField(default=True, help_text="Include today's scheduled memories")),
                ('include_weather', models.BooleanField(default=False, help_text='Include weather information')),
                ('include_quote', models.BooleanField(default=True, help_text='Include daily motivational quote')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wakeup_calls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Wakeup Calls',
                'ordering': ['wakeup_time'],
            },
        ),
    ]
