# Generated by Django 5.2.4 on 2025-08-08 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0010_add_wakeup_call_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WakeupCall',
        ),
    ]
