# Generated by Django 5.2.4 on 2025-08-08 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0012_add_notification_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
