# Generated by Django 5.2.4 on 2025-08-09 07:11

import memory_assistant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0013_remove_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional image to attach to this memory', null=True, upload_to=memory_assistant.models.memory_image_path),
        ),
    ]
