# Generated by Django 5.2.4 on 2025-08-10 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0015_memory_allow_comments_memory_allow_likes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('time_based', 'Time Based'), ('date_based', 'Date Based'), ('frequency_based', 'Frequency Based'), ('location_based', 'Location Based'), ('context_based', 'Context Based')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('trigger_conditions', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('next_trigger', models.DateTimeField(blank=True, null=True)),
                ('memory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_reminders', to='memory_assistant.memory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='smart_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('memory', 'user', 'reminder_type')},
            },
        ),
        migrations.CreateModel(
            name='ReminderTrigger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('trigger_reason', models.TextField()),
                ('was_dismissed', models.BooleanField(default=False)),
                ('was_acted_upon', models.BooleanField(default=False)),
                ('action_taken', models.TextField(blank=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='memory_assistant.smartreminder')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
    ]
