# Generated by Django 5.2.4 on 2025-08-10 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0016_smartreminder_remindertrigger'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_timezone',
            field=models.CharField(default='America/New_York', help_text="User's preferred timezone", max_length=50),
        ),
    ]
