# Generated by Django 5.2.4 on 2025-08-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0017_add_timezone_to_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_timezone',
            field=models.CharField(choices=[('UTC', 'UTC'), ('America/New_York', 'Eastern Time (US & Canada)'), ('America/Chicago', 'Central Time (US & Canada)'), ('America/Denver', 'Mountain Time (US & Canada)'), ('America/Los_Angeles', 'Pacific Time (US & Canada)'), ('America/Anchorage', 'Alaska Time'), ('Pacific/Honolulu', 'Hawaii Time'), ('Europe/London', 'London'), ('Europe/Paris', 'Paris'), ('Europe/Berlin', 'Berlin'), ('Europe/Moscow', 'Moscow'), ('Asia/Tokyo', 'Tokyo'), ('Asia/Shanghai', 'Shanghai'), ('Asia/Kolkata', 'India'), ('Australia/Sydney', 'Sydney'), ('Pacific/Auckland', 'Auckland')], default='America/New_York', help_text="User's preferred timezone", max_length=50),
        ),
    ]
