# Generated by Django 5.2.4 on 2025-08-12 07:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0018_alter_userprofile_user_timezone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='achievement_type',
            field=models.CharField(choices=[('goal', 'Goal'), ('task', 'Task'), ('milestone', 'Milestone'), ('habit', 'Habit'), ('project', 'Project'), ('learning', 'Learning Goal'), ('personal', 'Personal Achievement'), ('work', 'Work Achievement'), ('other', 'Other')], default='goal', help_text='Type of achievement this memory represents', max_length=50),
        ),
        migrations.AddField(
            model_name='memory',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When this achievement was completed', null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='is_achievement',
            field=models.BooleanField(default=False, help_text='Whether this memory represents a goal or achievement'),
        ),
        migrations.AddField(
            model_name='memory',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Whether this achievement has been completed'),
        ),
        migrations.AddField(
            model_name='memory',
            name='progress',
            field=models.IntegerField(default=0, help_text='Progress percentage (0-100) for this achievement'),
        ),
        migrations.AddField(
            model_name='memory',
            name='target_date',
            field=models.DateTimeField(blank=True, help_text='Target completion date for this achievement', null=True),
        ),
        migrations.CreateModel(
            name='AchievementStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_achievements', models.PositiveIntegerField(default=0, help_text='Total number of achievements created')),
                ('completed_achievements', models.PositiveIntegerField(default=0, help_text='Number of completed achievements')),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Current completion streak')),
                ('longest_streak', models.PositiveIntegerField(default=0, help_text='Longest completion streak')),
                ('total_completion_time', models.DurationField(default=datetime.timedelta(0), help_text='Total time spent on achievements')),
                ('last_completion_date', models.DateTimeField(blank=True, help_text='Date of last achievement completion', null=True)),
                ('goals_completed', models.PositiveIntegerField(default=0)),
                ('tasks_completed', models.PositiveIntegerField(default=0)),
                ('milestones_completed', models.PositiveIntegerField(default=0)),
                ('habits_completed', models.PositiveIntegerField(default=0)),
                ('projects_completed', models.PositiveIntegerField(default=0)),
                ('learning_goals_completed', models.PositiveIntegerField(default=0)),
                ('personal_achievements_completed', models.PositiveIntegerField(default=0)),
                ('work_achievements_completed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='achievement_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Achievement Statistics',
            },
        ),
    ]
