# Generated by Django 5.2.4 on 2025-08-12 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0019_memory_achievement_type_memory_completed_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='achievement_type',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='is_achievement',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='progress',
        ),
        migrations.RemoveField(
            model_name='memory',
            name='target_date',
        ),
        migrations.DeleteModel(
            name='AchievementStats',
        ),
    ]
