# Generated by Django 5.2.4 on 2025-08-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0020_remove_achievement_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When this memory was completed', null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='decline_reason',
            field=models.CharField(blank=True, help_text='Reason for declining the memory', max_length=200),
        ),
        migrations.AddField(
            model_name='memory',
            name='declined_at',
            field=models.DateTimeField(blank=True, help_text='When this memory was declined', null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Whether this scheduled memory has been completed'),
        ),
        migrations.AddField(
            model_name='memory',
            name='last_snoozed_at',
            field=models.DateTimeField(blank=True, help_text='When this memory was last snoozed', null=True),
        ),
        migrations.AddField(
            model_name='memory',
            name='snooze_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this memory has been snoozed'),
        ),
    ]
