# Generated by Django 5.2.4 on 2025-08-15 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0021_add_scheduled_memory_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='memory',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic'), ('fa', 'Persian'), ('zh', 'Chinese'), ('ru', 'Russian'), ('ja', 'Japanese')], default='en', help_text='Language of the memory content', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_language',
            field=models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French'), ('de', 'German'), ('ar', 'Arabic'), ('fa', 'Persian'), ('zh', 'Chinese'), ('ru', 'Russian'), ('ja', 'Japanese')], default='en', help_text="User's preferred language for TTS and UI", max_length=10),
        ),
    ]
