# Generated by Django 5.2.4 on 2025-08-16 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0022_memory_language_userprofile_user_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user_language',
        ),
    ]
