# Generated by Django 5.2.4 on 2025-08-16 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0023_remove_userprofile_user_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'created_at'], name='memory_assi_user_id_dcdb04_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'memory_type'], name='memory_assi_user_id_b49b6f_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'importance'], name='memory_assi_user_id_2c6285_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'is_archived'], name='memory_assi_user_id_eea8fd_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['content'], name='memory_assi_content_93e765_idx'),
        ),
        migrations.AddIndex(
            model_name='memory',
            index=models.Index(fields=['user', 'is_archived', 'created_at'], name='memory_assi_user_id_9e380a_idx'),
        ),
    ]
