# Generated by Django 5.2.4 on 2025-08-17 16:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memory_assistant', '0024_add_search_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sharedmemory',
            index=models.Index(fields=['shared_with_user', 'is_active'], name='memory_assi_shared__a05eb6_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedmemory',
            index=models.Index(fields=['shared_with_organization', 'is_active'], name='memory_assi_shared__a1d723_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedmemory',
            index=models.Index(fields=['memory', 'is_active'], name='memory_assi_memory__30f615_idx'),
        ),
        migrations.AddIndex(
            model_name='sharedmemory',
            index=models.Index(fields=['is_active', 'created_at'], name='memory_assi_is_acti_a7de05_idx'),
        ),
    ]
